# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awsserver',
            old_name='private_ip',
            new_name='private_ip_address',
        ),
        migrations.RenameField(
            model_name='awsserver',
            old_name='public_ip',
            new_name='public_ip_address',
        ),
        migrations.RenameField(
            model_name='awsserver',
            old_name='vpc',
            new_name='vpc_id',
        ),
        migrations.RemoveField(
            model_name='awsserver',
            name='cost_by_month',
        ),
        migrations.RemoveField(
            model_name='awsserver',
            name='server_price_by_hour',
        ),
        migrations.RemoveField(
            model_name='awsserver',
            name='volumes_price',
        ),
        migrations.AddField(
            model_name='awsserver',
            name='overall_cost_by_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='awsserver',
            name='server_cost_by_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='awsserver',
            name='volumes_overall_cost',
            field=models.FloatField(default=0),
        ),
    ]
