# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import ownservers.models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0002_auto_20170131_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('public_ip_address', models.CharField(max_length=250)),
                ('private_ip_address', models.CharField(max_length=250)),
                ('vpc_id', models.CharField(max_length=250)),
                ('server_cost_by_hour', models.FloatField(default=0)),
                ('volumes', models.CharField(max_length=250)),
                ('volumes_overall_cost', models.FloatField(default=0)),
                ('overall_cost_by_month', models.FloatField(default=0)),
                ('launch_time', models.DateTimeField(blank=True, default=ownservers.models.current_date)),
                ('scheduled', models.DateTimeField(blank=True, default=ownservers.models.current_date)),
            ],
        ),
        migrations.DeleteModel(
            name='AWSServer',
        ),
    ]
