# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0003_auto_20170131_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2servers',
            name='security_group',
            field=models.CharField(default='sec-group', max_length=250),
            preserve_default=False,
        ),
    ]
