# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0004_ec2servers_security_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2servers',
            name='volumes_cost',
            field=models.FloatField(default=0),
        ),
    ]
