# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0005_ec2servers_volumes_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2servers',
            name='volumes_overall_cost',
        ),
    ]
