# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0006_remove_ec2servers_volumes_overall_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2servers',
            name='private_ip_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ec2servers',
            name='public_ip_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
