# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownservers', '0007_auto_20170131_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2servers',
            name='instance_id',
            field=models.CharField(default='id', max_length=250),
            preserve_default=False,
        ),
    ]
